**Logistic Regression:
Apply logistic regression on the Loan dataset with "Decision" as the dependent variable. Do the necessary one-hot encoding for the categorical variables and discard the irrelevant variables. Use whatever libraries are appropriate when coding in Python.**

In [1]:
import pandas as pd
import numpy as np

In [2]:
loan_data=pd.read_excel('loan.xlsx')

In [3]:
print(loan_data.shape)
loan_data

(429, 14)


Sex        Age  Time_at_address Res_status  Telephone Occupation  \
0     M  50.750000            0.585      owner      given  unemploye   
1     M  19.670000           10.000       rent  not_given   labourer   
2     F  52.830002           15.000      owner      given  creative_   
3     M  22.670000            2.540       rent  not_given  creative_   
4     M  29.250000           13.000      owner      given     driver   
..   ..        ...              ...        ...        ...        ...   
424   M  34.169998            2.750      owner      given  guard_etc   
425   F  22.250000            1.250       rent  not_given  unemploye   
426   M  23.330000            1.500      owner      given  creative_   
427   M  21.000000            4.790       rent  not_given  productio   
428   M  27.750000            1.290      owner      given   labourer   

    Job_status  Time_employed  Time_bank Liab_ref    Acc_ref  Home_Expn  \
0    unemploye              0          0        f      given        145   
1    governmen              0          0        t      given        140   
2    private_s              5         14        f      given          0   
3    governmen              2          0        f      given          0   
4    governmen              0          0        f      given        228   
..         ...            ...        ...      ...        ...        ...   
424  self_empl              2          0        t      given        232   
425  unemploye              3          0        f      given        280   
426  governmen              1          0        f      given        422   
427  private_s              2          1        t      given         80   
428  governmen              0          0        t  oth_inst_        140   

     Balance Decision  
0          0   reject  
1          0   reject  
2       2200   accept  
3          0   accept  
4          0   reject  
..       ...      ...  
424      200   reject  
425        0   reject  
426      200   accept  
427      300   accept  
428        0   reject  

[429 rows x 14 columns]

In [4]:
loan_data.isnull().sum()

Sex                0
Age                0
Time_at_address    0
Res_status         0
Telephone          0
Occupation         0
Job_status         0
Time_employed      0
Time_bank          0
Liab_ref           0
Acc_ref            0
Home_Expn          0
Balance            0
Decision           0
dtype: int64

In [5]:
loan_data.head()
loan_data.shape

(429, 14)

In [6]:
X=loan_data.iloc[:,:-1].values
X

array([['M', 50.75, 0.584999978542328, ..., 'given', 145, 0],
       ['M', 19.6700000762939, 10.0, ..., 'given', 140, 0],
       ['F', 52.8300018310547, 15.0, ..., 'given', 0, 2200],
       ...,
       ['M', 23.3299999237061, 1.5, ..., 'given', 422, 200],
       ['M', 21.0, 4.78999996185303, ..., 'given', 80, 300],
       ['M', 27.75, 1.28999996185303, ..., 'oth_inst_', 140, 0]],
      dtype=object)

In [7]:
y=loan_data.iloc[:,-1].values

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0,3,4,5,6,9,10])],remainder='passthrough')
x=np.array(ct.fit_transform(X))

In [9]:

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [10]:
print(x)
print(x.shape)

[[0.0 1.0 1.0 ... 0 145 0]
 [0.0 1.0 0.0 ... 0 140 0]
 [1.0 0.0 1.0 ... 14 0 2200]
 ...
 [0.0 1.0 1.0 ... 0 422 200]
 [0.0 1.0 0.0 ... 1 80 300]
 [0.0 1.0 1.0 ... 0 140 0]]
(429, 35)


In [11]:
print(y.shape)

(429,)


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [13]:
print(X_train)
print(y_train.shape)
print(X_test)
print(y_test.shape)

[[0.0 1.0 1.0 ... 6 70 0]
 [1.0 0.0 1.0 ... 7 0 0]
 [1.0 0.0 1.0 ... 1 220 19]
 ...
 [0.0 1.0 1.0 ... 1 96 19]
 [0.0 1.0 1.0 ... 0 360 0]
 [1.0 0.0 1.0 ... 1 108 98]]
(343,)
[[0.0 1.0 1.0 ... 0 221 0]
 [0.0 1.0 1.0 ... 12 0 221]
 [0.0 1.0 1.0 ... 1 420 283]
 ...
 [1.0 0.0 0.0 ... 0 280 0]
 [1.0 0.0 1.0 ... 3 0 0]
 [1.0 0.0 1.0 ... 0 280 0]]
(86,)


In [14]:
from sklearn.linear_model import LogisticRegression

logmodel = LogisticRegression(max_iter=10000)
logmodel.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [15]:
logmodel.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [16]:
prediction= logmodel.predict(X_test)

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.92      0.53      0.68        45
           1       0.65      0.95      0.77        41

    accuracy                           0.73        86
   macro avg       0.79      0.74      0.72        86
weighted avg       0.79      0.73      0.72        86



In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,prediction)
print(cm)
accuracy_score(y_test,prediction)

[[24 21]
 [ 2 39]]


0.7325581395348837